#Comentario
    do re mi fa sol la si do
    DECLARA "pipo" COMO CANCION
    EL TEMPO = 112
    pipo ESTA EN CLAVESOL
    pipo ESTA EN CUATROCUARTOS
    ARMADURA = DOMAYOR
    INSERTAR 4 do NATURAL AGUDO COMO CORCHEA
    ELIMINAR pipo
    HACER EL sol = SOSTENIDO
    INSERTAR UN la GRAVE CON ACENTO
    INSERTAR UN si PPP
EJECUTAR CANCION
